### ISSUE TITLE
Add axios proxy example to the readme

### ISSUE THREAD

**Issue by kepikoi** [Tangany/waas-js-sdk#23]
It is possible to modify the axios settings via the exposed axios object from a Waas instance like this:
```
const waas = new Waas();
const axios = waas.axios;
axios.defaults.proxy = {
    host: Proxy.host,
    port: Proxy.port,
    auth: {
        username: Proxy.username,
        password: Proxy.password
    }
};
```

This option should be documented in some way in the readme

**Comment by adrianmitter** [comment]
What would be a typical use case where you set these options manually? I would like to explain this briefly in the README, so that I don't just provide a code snippet that might be misunderstood without an exemplary use case. I have no use case in mind, but you certainly had one (or a group of cases) in mind when you posted the issue. 

I assume that users only use this option in exceptional cases, right? I would add that to avoid giving the impression that you need it for a "normal" instantiation of the SDK.

**Comment by kepikoi** [comment]
One example use case would be tunnel all SDK requests through a user-defined proxy. This is possible due to the exposed axios object in the SDK and is not mandatory for standard operations
