### ISSUE TITLE
Provide compatibility with WaaS 1.6

### ISSUE THREAD

**Issue by kepikoi** [Tangany/waas-js-sdk#47]
https://github.com/Tangany/Wallet-as-a-Service/blob/master/CHANGELOG.md#161---2020-08-12

**Comment by adrianmitter** [comment]
# Call Ethereum smart contract methods

The implementation of the following new endpoints is described:
- `POST /eth/contract/:contract/call`
- `GET /eth/contract/:contract/call/:method`
- `POST /eth/contract/:contract/:wallet/call`
- `GET /eth/contract/:contract/:wallet/call/:method`

Shared definitions:
```typescript
interface IContractCall {
    function: string;
    outputs: string[];
    inputs: string[];
}

type ContractCallResult = { type: string | null; value: string | null; }[];
```

For wallet-based and wallet-independent calls, such a method `call` should be implemented in each case, so that the following snippets are possible:
```typescript
public async call(config: IContractCall): Promise<ContractCallResult>;
public async call(method: string, types?: string[]): Promise<ContractCallResult>;
public async call(config: IContractCall | string, types?: string[]): Promise<ContractCallResult> {
    // Throw an error if the first argument is an object and the second parameter was used
}

new Waas().eth().contract(tokenAddress).call("symbol", ["string"]);
new Waas().eth().contract("").call({
    function: "balanceOf(address)",
    inputs: ["0x2133213.."],
    outputs: ["uint256"]
});

// Wallet-based contract call
const contract = new Waas().wallet("my-wallet").eth().contract(tokenAddress);
contract.call("getBalance", ["string"]);
contract.call({
    function: "getCaller()",
    inputs: [],
    outputs: ["address"]
});
```

# Sweep Bitcoin wallet

For `POST /btc/wallet/:wallet/sweep-async` the following method shall be implemented:
```typescript
public async sweepAsync({to, wallet}: {to?: string, wallet?: string}): Promise<Request>;

const req = await new Waas().wallet("my-wallet").btc().sweepAsync({to: "tb1q3dfd2wq93jwhtcshv2faaq0yxch0w8v6tv65x4"});
const { process, status, output } = await req.get();
```

This endpoint returns a status URI for the asynchronous request executed in the background.
From this, a `Request` object is to be created and returned, as for example with `sendAsync()`:
https://github.com/Tangany/waas-js-sdk/blob/1c0d60b92bb8e4d00bb956ad4fc5b6adb433a7b2/src/eth-wallet.ts#L65-L71

# Wallet substition

The SDK methods for the listed endpoints use the `IRecipient` interface, so only one change is required:
- `POST eth/wallet/:wallet/send`,
- `POST eth/wallet/:wallet/send-async`,
- `POST eth/wallet/:wallet/sign`
- `POST eth/wallet/:wallet/estimate-fee`
- `POST /eth/erc20/:token/:wallet/send`
- `POST btc/wallet/:wallet/send`
- `POST btc/wallet/:wallet/sign`
- `POST btc/wallet/:wallet/estimate-fee`

The endpoints `POST /eth/contract/:contract/call` and `POST /eth/contract/:contract/:wallet/call` are new in WaaS 1.6.
The wallet substitution is implemented according to the approach described above.

# Parameter "amount"

The endpoint `POST /eth/contract/:contract/:wallet/send-async` now supports an optional property "amount" in the request body.
For this purpose the parameter object of the method must be extended by `amount?: string`.

At the same time, the specification of "amount" in all Ethereum endpoints sent is also optional:
- many of the affected SDK methods use IRecipient, so one change is sufficient
- in `src/eth-erc20-wallet.ts` you have to adjust `approve()`, `transferFrom()`, `burn()` and `mint`

**Comment by kepikoi** [comment]
Looks great to me. Please proceed to the implementation phase 👍
